### ISSUE TITLE
Put a pom.xml!

### ISSUE THREAD

**Issue by jbarros35** [virgo47/restful-spring-security#1]
The world needs maven and you insist only using gradle? its not helping anyone.

**Comment by virgo47** [comment]
Uff, I don't know what to say to this. This is no library that needs to be released on Maven Central anyway. Just copy/paste code you want.

If I wanted to build something with Ant's `build.xml`, I'd download Ant. If you want to build this, download Gradle. You may create the `pom.xml` file, I'll add it then. From what I know this was helpful for some people and none of them needed POM, so I can't take your "its not helping anyone" seriously at all. Add unnecessary exclamation mark (are you giving me orders?) and no wonder I'm not considering this issue at all.

BTW: "the world needs maven" - perhaps the world needs to move beyond Maven already (although I use Maven extensively myself).
